package com.briup.bean;

import java.io.Serializable;

public class SalChance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private Long chcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_source
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_cust_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_title
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_rate
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private Integer chcRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_linkman
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_tel
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_addr
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_desc
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_create_by
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcCreateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_due_to
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcDueTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_status
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String chcStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sal_chance
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_id
     *
     * @return the value of sal_chance.chc_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public Long getChcId() {
        return chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_id
     *
     * @param chcId the value for sal_chance.chc_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcId(Long chcId) {
        this.chcId = chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_source
     *
     * @return the value of sal_chance.chc_source
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcSource() {
        return chcSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_source
     *
     * @param chcSource the value for sal_chance.chc_source
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcSource(String chcSource) {
        this.chcSource = chcSource == null ? null : chcSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_cust_name
     *
     * @return the value of sal_chance.chc_cust_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcCustName() {
        return chcCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_cust_name
     *
     * @param chcCustName the value for sal_chance.chc_cust_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcCustName(String chcCustName) {
        this.chcCustName = chcCustName == null ? null : chcCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_title
     *
     * @return the value of sal_chance.chc_title
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcTitle() {
        return chcTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_title
     *
     * @param chcTitle the value for sal_chance.chc_title
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcTitle(String chcTitle) {
        this.chcTitle = chcTitle == null ? null : chcTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_rate
     *
     * @return the value of sal_chance.chc_rate
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public Integer getChcRate() {
        return chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_rate
     *
     * @param chcRate the value for sal_chance.chc_rate
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcRate(Integer chcRate) {
        this.chcRate = chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_linkman
     *
     * @return the value of sal_chance.chc_linkman
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcLinkman() {
        return chcLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_linkman
     *
     * @param chcLinkman the value for sal_chance.chc_linkman
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcLinkman(String chcLinkman) {
        this.chcLinkman = chcLinkman == null ? null : chcLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_tel
     *
     * @return the value of sal_chance.chc_tel
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcTel() {
        return chcTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_tel
     *
     * @param chcTel the value for sal_chance.chc_tel
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcTel(String chcTel) {
        this.chcTel = chcTel == null ? null : chcTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_addr
     *
     * @return the value of sal_chance.chc_addr
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcAddr() {
        return chcAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_addr
     *
     * @param chcAddr the value for sal_chance.chc_addr
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcAddr(String chcAddr) {
        this.chcAddr = chcAddr == null ? null : chcAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_desc
     *
     * @return the value of sal_chance.chc_desc
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcDesc() {
        return chcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_desc
     *
     * @param chcDesc the value for sal_chance.chc_desc
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcDesc(String chcDesc) {
        this.chcDesc = chcDesc == null ? null : chcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_create_by
     *
     * @return the value of sal_chance.chc_create_by
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcCreateBy() {
        return chcCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_create_by
     *
     * @param chcCreateBy the value for sal_chance.chc_create_by
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcCreateBy(String chcCreateBy) {
        this.chcCreateBy = chcCreateBy == null ? null : chcCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_due_to
     *
     * @return the value of sal_chance.chc_due_to
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcDueTo() {
        return chcDueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_due_to
     *
     * @param chcDueTo the value for sal_chance.chc_due_to
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcDueTo(String chcDueTo) {
        this.chcDueTo = chcDueTo == null ? null : chcDueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_status
     *
     * @return the value of sal_chance.chc_status
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getChcStatus() {
        return chcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_status
     *
     * @param chcStatus the value for sal_chance.chc_status
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setChcStatus(String chcStatus) {
        this.chcStatus = chcStatus == null ? null : chcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chcId=").append(chcId);
        sb.append(", chcSource=").append(chcSource);
        sb.append(", chcCustName=").append(chcCustName);
        sb.append(", chcTitle=").append(chcTitle);
        sb.append(", chcRate=").append(chcRate);
        sb.append(", chcLinkman=").append(chcLinkman);
        sb.append(", chcTel=").append(chcTel);
        sb.append(", chcAddr=").append(chcAddr);
        sb.append(", chcDesc=").append(chcDesc);
        sb.append(", chcCreateBy=").append(chcCreateBy);
        sb.append(", chcDueTo=").append(chcDueTo);
        sb.append(", chcStatus=").append(chcStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}