package com.briup.bean;

import java.io.Serializable;

public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.usr_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.usr_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String usrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.usr_password
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private String usrPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.usr_flag
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private Integer usrFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.usr_role_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private Long usrRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.usr_id
     *
     * @return the value of sys_user.usr_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.usr_id
     *
     * @param usrId the value for sys_user.usr_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.usr_name
     *
     * @return the value of sys_user.usr_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.usr_name
     *
     * @param usrName the value for sys_user.usr_name
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName == null ? null : usrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.usr_password
     *
     * @return the value of sys_user.usr_password
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public String getUsrPassword() {
        return usrPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.usr_password
     *
     * @param usrPassword the value for sys_user.usr_password
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword == null ? null : usrPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.usr_flag
     *
     * @return the value of sys_user.usr_flag
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public Integer getUsrFlag() {
        return usrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.usr_flag
     *
     * @param usrFlag the value for sys_user.usr_flag
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setUsrFlag(Integer usrFlag) {
        this.usrFlag = usrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.usr_role_id
     *
     * @return the value of sys_user.usr_role_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public Long getUsrRoleId() {
        return usrRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.usr_role_id
     *
     * @param usrRoleId the value for sys_user.usr_role_id
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    public void setUsrRoleId(Long usrRoleId) {
        this.usrRoleId = usrRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Mar 04 14:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", usrId=").append(usrId);
        sb.append(", usrName=").append(usrName);
        sb.append(", usrPassword=").append(usrPassword);
        sb.append(", usrFlag=").append(usrFlag);
        sb.append(", usrRoleId=").append(usrRoleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}